server:
  port: 8787
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:file:/Users/yu/Desktop/test/h2/demo
    username: sa
    password: password
    driverClassName: org.h2.Driver